handle only one temporal window in temporalCovariateSettings
OHDSI/FeatureExtraction pull request #234
Opened 2024-02-23 13:15 UTC by ginberg

see #200 
The error happens in the Java function 'createSql'; it can't handle if the temporalEndDays is a single value. At first we thought we should add a check in the createTemporalCovariateSettings function (and a couple of related function) so that the user needs to provide a list in case of a single value. But after looking into it, I found that we can solve it in the Java code and so we don't need to make any (possibly breaking) changes.

Also, I have updated the json jar, since we recently updated the version in the pom file. See https://github.com/OHDSI/FeatureExtraction/pull/217

2024-02-23 14:48 UTC, schuemie approved these changes

2024-02-26 15:07 UTC, anthonysena commented on java/org/ohdsi/featureExtraction/FeatureExtraction.java
> +			jsonWriter.value(timeIdIndexArray);
@ginberg do we need similar handling for the `start_day` parameter?

2024-02-26 15:08 UTC, anthonysena requested changes
Looks good - just had one question before approving. Thanks!

2024-02-26 15:57 UTC, ginberg commented on java/org/ohdsi/featureExtraction/FeatureExtraction.java
> +			jsonWriter.value(timeIdIndexArray);
@anthonysena we don't need to do that. Since the problem happens when creating the value for the time_id variable and that one uses only the endDays value. See [code](https://github.com/OHDSI/FeatureExtraction/blob/develop/java/org/ohdsi/featureExtraction/FeatureExtraction.java#L594-L603)

2024-02-26 16:20 UTC, anthonysena approved these changes

2024-02-27 08:09 UTC, merged