add minimum threshold for covariate mean
OHDSI/FeatureExtraction pull request #238
Opened 2024-03-01 12:51 UTC by ginberg

see #174

2024-03-06 02:55 UTC, gowthamrao commented on R/GetDefaultCovariates.R
> +          dplyr::filter(.data$averageValue > minCharacterizationMean)
hi @ginberg - instead of filtering on R side, i think it is more useful to filter it in the sql itself. Filtering in the R side would definitely reduce the size of the final output, but it wont reduce the movement of data from db to the local R.

2024-03-06 02:55 UTC, gowthamrao requested changes
Would it be possible to implement the filter in sql?

2024-03-06 15:26 UTC, ginberg commented
hi @gowthamrao thanks for having a look at it. I agree that ideally we would filter on the database side. However, this is more complex. Partly because the related sql code ([for example](https://github.com/OHDSI/FeatureExtraction/blob/bb0213e64198b98e8fe80c3e964d308952779515/inst/sql/sql_server/CohortBasedCountCovariates.sql#L87) is already quite long and we need to make sure it works for all database platforms.
Also discussed this with @anthonysena We are thinking to go for a solution on the R-side first, just like they have done in CohortDiagnostics. If we find a solution on the db side (possibly after refactoring queries so they are less complex) we can update our solution. What do you think?

2024-03-06 20:37 UTC, gowthamrao commented
The CD approach is reasonable. But then I would think about the solution being a different independent function that modifies covariateData object.

modifyCovariateData? It could copy or overwrite, filter records? Essentially a helper function that manages and filters an Andromeda object with covariateData?

2024-03-22 16:03 UTC, ginberg commented
@gowthamrao a function that modifies the covariateData is not a bad idea. I called it a bit different since we are just filtering, we can rename it if we decide to change the functionality. See [change](https://github.com/OHDSI/FeatureExtraction/pull/238/commits/04fab4f49d0eb0a93d369358e6dd7bc43d54d397) Is this ok for you?

2024-03-29 13:12 UTC, anthonysena commented on R/GetDefaultCovariates.R
> +  if ("averageValue" %in% colnames(covariateData[[covariatesName]])) {
Let's exit the function if the `minCharacterizationMean` == 0 since we do not need to filter the covariateData.

2024-03-29 13:12 UTC, anthonysena requested changes
If we could address my small comment about the `minCharacterizationMean` then I think this is ready to merge.

2024-04-02 06:46 UTC, ginberg commented
@anthonysena that's a good point, I have added a check

2024-04-02 06:47 UTC, merged