documentation update
OHDSI/FeatureExtraction pull request #243
Opened 2024-04-16 12:14 UTC by ginberg

see #229

2024-04-16 19:10 UTC, ginberg commented
@anthonysena do you think this is enough with regard to updating the documentation or should we describe it somewhere else as well?

2024-04-19 13:24 UTC, anthonysena requested changes
From our discussion let's revise this and link back to the original issue so people can get more details as required.

2024-04-19 13:24 UTC, anthonysena commented on R/GetCovariates.R
> +#'                               per patient and per cohort. Otherwise there will be collisions and the output is ambiguous.
> If aggregated is set to FALSE, the cohort table should contain unique records per patient and per cohort. Otherwise there will be collisions and the output is ambiguous.

If aggregated is set to FALSE, the results returned will be based on each `subject_id` and `cohort_start_date` in your cohort table. If your cohort contains multiple entries for the same `subject_id` (due to different `cohort_start_date` values), you must carefully set the `rowIdField` so you can identify the patients properly See [Issue #229](https://github.com/OHDSI/FeatureExtraction/issues/229#issuecomment-1948623051) for more discussion on this parameter.

2024-05-21 11:49 UTC, ginberg commented on R/GetCovariates.R
> +#'                               per patient and per cohort. Otherwise there will be collisions and the output is ambiguous.
hi @anthonysena I have updated the documentation to the text above

2024-06-07 13:26 UTC, anthonysena approved these changes

2024-06-07 13:43 UTC, merged